---
# vim: ft=yaml
# docker-compose recipe for easiness
myjenkins:
  image: myjenkins_cloudfoundary_dood
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - ./jenkins_home:/var/jenkins_home
  ports:
    - "8080:8080"
    - "50000:50000"
